import dotenv from "dotenv";
import env from './env.js'

const envFound = dotenv.config({ path: `.env.${env}` });

if (envFound.error) {

  throw new Error("Couldn't find .env file.");
}

export default {

  PORT_SERVER:process.env.PORT_SERVER,

  OPENAI_API_KEY_GPT_35: process.env.OPENAI_API_KEY_GPT_35,
  OPENAI_API_KEY_GPT_4: process.env.OPENAI_API_KEY_GPT_4,
  OPENAI_ORGANIZATION: process.env.OPENAI_ORGANIZATION,

  DISCORD_TOKEN:process.env.DISCORD_TOKEN,
  DISCORD_TOKEN_LUCY:process.env.DISCORD_TOKEN_LUCY,
  BOT_IN_DISCORD_ID:process.env.BOT_IN_DISCORD_ID,
  CLIENT_ID:process.env.CLIENT_ID,
  CLIENT_SECRET:process.env.CLIENT_SECRET,
  GUILD_ID:process.env.GUILD_ID,
  NAME_BOT:process.env.NAME_BOT,
  API_ENDPOINT:process.env.API_ENDPOINT,
  REDIRECT_URI:process.env.REDIRECT_URI,
  REDIRECT_URI_ADD_BOT:process.env.REDIRECT_URI_ADD_BOT,
  GUILD_MANAGER_PERMISSION:process.env.GUILD_MANAGER_PERMISSION,
  
  URL_WEBHOOK_DISCORD_YOUTUBE:process.env.URL_WEBHOOK_DISCORD_YOUTUBE,
  URL_WEBHOOK_DISCORD_TWITTER:process.env.URL_WEBHOOK_DISCORD_TWITTER,
  URL_WEBHOOK_DISCORD_ON_MESSAGE:process.env.URL_WEBHOOK_DISCORD_ON_MESSAGE,
  URL_WEBHOOK_DISCORD_BACK_LUCY:process.env.URL_WEBHOOK_DISCORD_BACK_LUCY,
  URL_WEBHOOK_DISCORD_BOT:process.env.URL_WEBHOOK_DISCORD_BOT,

  ENCRYPT:process.env.ENCRYPT,

  MYSQL_HOSTNAME: process.env.MYSQL_HOSTNAME,
  MYSQL_USERNAME: process.env.MYSQL_USERNAME,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
  MYSQL_NAME: process.env.MYSQL_NAME,
  MYSQL_PORT: process.env.MYSQL_PORT,

  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,

  GOOGLE_API_KEY_0: process.env.GOOGLE_API_KEY_0,
  GOOGLE_API_KEY_1: process.env.GOOGLE_API_KEY_1,
  GOOGLE_API_KEY_2: process.env.GOOGLE_API_KEY_2,
  GOOGLE_API_KEY_3: process.env.GOOGLE_API_KEY_3,
  GOOGLE_API_KEY_4: process.env.GOOGLE_API_KEY_4,

  TWITTER_BEARER_TOKEN:process.env.TWITTER_BEARER_TOKEN,
  TWITTER_API_KEY:process.env.TWITTER_API_KEY,
  TWITTER_API_KEY_SECRET:process.env.TWITTER_API_KEY_SECRET,
  TWITTER_ACCESS_TOKEN_SECRET:process.env.TWITTER_ACCESS_TOKEN_SECRET,
  TWITTER_ACCESS_TOKEN:process.env.TWITTER_ACCESS_TOKEN,

  TWITTER_API_URL:process.env.TWITTER_API_URL,

  WPP_LUCAO_USER: process.env.WPP_LUCAO_USER,
  WPP_LUCAO_KEY: process.env.WPP_LUCAO_KEY,

  SERVER_DISCORD_ID_MAIN: process.env.SERVER_DISCORD_ID_MAIN,
  CATEGORY_DISCORD_ID_LOGS: process.env.CATEGORY_DISCORD_ID_LOGS,

  GPT_API_FREE_URL: process.env.GPT_API_FREE_URL

};
